version: '3'
services:
  babel-node-starter:
    container_name: babel-node-starter
    image: babel-node-starter
    command: sh docker-entrypoint.sh
    env_file:
      - docker-variables.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    ports:
     - "3000:3000"